server.port=8080
spring.datasource.url=jdbc:h2:mem:keystone
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.jpa.show-sql=false
jwt.secret=MySuperSecretKeyForKeystoneProject32CharsLong123456
